import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import { Toaster } from "react-hot-toast";
import { setCookie } from "nookies";

import { Alert } from "@/src/components/utils/toast/toast";
import requestAxios from "@/infra/api/request/request";

export default function Login() {

  const router = useRouter();

  const [user, setUser] = useState({ user: "", password: "" });

  function onChange(event: any) {
    const { name, value } = event.target;
    setUser({ ...user, [name]: value });
  }

  async function onSubmit(event: any) {
    event.preventDefault();

    if (user?.user == "" || user?.password == "") {
      return;
    }

    const responseAxios = await requestAxios(user);

    if (responseAxios.Message?.Token.length > 0) {
      
      setCookie(null, "Next_User", `${JSON.stringify(responseAxios.Message)}`, {
        maxAge: 30 * 24 * 60 * 60,
        path: "*",
      });

      Alert.notifySucess("User successfully logged in!");

      return setTimeout(() => {
        router.push("/home");
      }, 2000);
    }

    Alert.notifyError("Incorrect username or password!");
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <div className="container d-flex flex-column justify-content-center align-itens-center text-center vh-100">
          <main className="form-signin w-100 m-auto">
            <form onSubmit={onSubmit} className="container w-100">
              <i
                style={{ fontSize: "64px" }}
                className="bi bi-chat-left-dots-fill"
              ></i>
              <h1 className="h3 mb-3 fw-normal">Please sign in</h1>

              <div className="form-floating py-1">
                <input
                  type="email"
                  className="form-control"
                  id="floatingInput"
                  placeholder="name@example.com"
                  name="user"
                  autoComplete="false"
                  onChange={onChange}
                />
                <label htmlFor="floatingInput">Email address</label>
              </div>

              <div className="form-floating py-1">
                <input
                  type="password"
                  className="form-control"
                  id="floatingPassword"
                  placeholder="Password"
                  name="password"
                  autoComplete="false"
                  onChange={onChange}
                />
                <label htmlFor="floatingPassword">Password</label>
              </div>

              <div className="checkbox my-3" />

              <button className="w-100 btn btn-lg btn-primary" type="submit">
                Sign in
              </button>
            </form>
          </main>
          <Toaster />
        </div>
      </>
    </>
  );
}
